server:
  port: 9527

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myBatisTest
    username: root
    password: 123456

  mybatis:
  type-aliases-package: com.cmp.model
  mapper-locations:
    -mapper/*

